### ISSUE TITLE
#186 - Can place a road in setup round where you will not be able to build a settlement

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#125]
Steps to reproduce:
1. In the setup round place a road and a settlement
2. Have another player build a road and settlement (road is 2 edges away, settlement is 3 vertices away) See picture for placement.
3. When your turn comes again, you can place a road between the two existing roads, but cannot place a settlement on either end of the road, stopping you from progressing through the game.

What is the expected output? What do you see instead?
You shouldn't be allowed to place a road there

**Comment by sgtpepper43** [comment]
Just switch to placing settlements first

**Comment by enexia79** [comment]
fixed
