### ISSUE TITLE
#383 - If you have 9 points and earn Longest Road, the game doesn't end

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#131]
What steps will reproduce the problem?
1. Earn 9 victory points (In this case, I also had largest army)
2. Build enough roads to earn longest road
3. The game doesn't declare you as the winner and you can continue to build roads. The map doesn't show that a road was placed but you can continue to "build" roads off subsequent roads placed.

What is the expected output? What do you see instead?
The expected output would be to show the game winner modal but it doesn't. Longest road is also not awarded to the player

**Comment by joshuata** [comment]
Note by ChadSBacon:
> I just reproduced this, then I viewed the model on the server's Swagger page using game/model. The server is definitely assigning a winner. Your code was throwing an IllegalArgumentException: "invalid points value".
> We had this same bug with our client. For us it was the PointsController that was causing it. It's a pretty significant bug; the game doesn't end and everything gets buggy after it happens.

**Comment by joshuata** [comment]
Note by ChadSBacon:
> Also, if you're playing with multiple clients, the clients who didn't win will correctly have the "You lose" modal pop up. But nothing happens for the winner, and his points in the bottom left corner stay at 9.

**Comment by enexia79** [comment]
this is a bug in the UI.. the work around is localPlayer.getVictoryPoints() >= 10 ? 10 : localPlayer.getVictoryPoints().  So hopefully they wont take points from us for their issue.
