### ISSUE TITLE
#475 - Can repeatedly play the knight card when holding 2+ knights

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#136]
What steps will reproduce the problem?
1. Obtain 2 knight cards
2. Wait a turn for them to be playable
3. Play a knight card normally
4. Continue to play that same card as many times as desired

Result:
- the first time playing knight card is normal
- the second time, the modal pops up and you can place the robber and choose who to steal from, but the resources don't actually get transferred and the robber stays put
- the knight card count doesn't actually get decremented until the turn ends

**Comment by joshuata** [comment]
Note by behatdude:
> Correction: the knight card count gets decremented immediately for the first knight, but doesn't decrement for the following uses.

**Comment by enexia79** [comment]
I already fixed this one
