### ISSUE TITLE
#488 - Settlement/City/Road buttons are not disabled when depleted

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#137]
What steps will reproduce the problem?
1. Build all of a players roads/settlements/cities

Expected:
Once all of a type of piece is used up, the piece icon should be disabled

Actual:
You can still click the icon for the expired piece, which brings up the map modal. However, the map indicates that no position is valid to place the piece.

**Comment by enexia79** [comment]
I already fixed this while fixing another bug in the same place
