### ISSUE TITLE
#515 - Can lock game using road building dev card twice

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#139]
What steps will reproduce the problem?
1. Obtain the road building dev card
2. Play the card and place your second road in the water
3. Play the card again and try to place the roads normally

Expected:
Assuming you're allowed to use the card twice, the game should allow both roads to be placed in valid positions.

Actual:
The first road can be played, but the game blocks on the second road because it says no place on the map is a valid location.

**Comment by joshuata** [comment]
Note by behatdude:
> The only thing this has in common with the other issue is the water placement. The real problem here is with the RoadBuilding card locking/preventing gameplay during the second road placement.
> **Fixing the water problem will not necessarily fix this issue because it has happens sometimes without the water placement. That is just a sure-fire way to reproduce the problem.**

**Comment by enexia79** [comment]
They have 2 steps in this that are no longer possible after fixing other bugs.. this can not be duplicated and is most certainly simply another symptom of the same bug already fixed be it issue 525 or 511 or both..  but even if it was both it still shouldn't be counted as a separate bug.
