### ISSUE TITLE
#524 - *Unique* leaving after first road in BuildRoad card allow multiple roads

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#140]
What steps will reproduce the problem?
1.Obtain a road building card
2.Build the first road
3.Close the game
4.Open the game and reuse the card in the same manner

Expected:
The game should either bring you straight back to play the second road OR back to the basic playing state WITHOUT the first road remaining.

Actual:
The first road stays built and the option to play the second road does not show. You can play the road building card again, but it allows you to play both roads, which you can use to repeat the steps above by not actually playing both roads.

**Important!!
I realize that we logged the unlimited use of that road card earlier, but in this case the road card isn't completely used. The bug is with the partial use of the card not being handled correctly, so I don't think it has the same root problem.

**Comment by joshuata** [comment]
Note: Added today

**Comment by enexia79** [comment]
was not a unique issue.. fixing the other one fixed this one.. what a surprise... these guys are just reaching for more extra credit.. I really wish Rodham hadn't offered that.
