### ISSUE TITLE
#524 - Using RoadBuilding card when out of roads locks the game

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#141]
What steps will reproduce the problem?
1.Obtain the road building card
2.Build all of your roads
3.Play the road building card

Expected:
Either the card should be completely disabled OR there should be a cancel button to let you back out.

Actual:
The road building card is playable and the map modal open to allow road placement. Because there are no roads left, the map shows every edge as an invalid building position, but there is no cancel to back out, so you're stuck.

After following these steps, the game is locked and must be closed, then reopened to continue.

**Comment by enexia79** [comment]
fixed
