### ISSUE TITLE
#536 - View dev card modal not enabled when you have only a monument

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#142]
What steps will reproduce the problem?
1. Start with 0 dev cards
2. Buy a card and hope that you get lucky and get a monument
3. Wait until you next turn
4. If enabled, open dev card modal and use the card, then buy another card
5. If disabled, you have a monument
6. Can verify by buying another dev card, which enables the dev card modal

Expected:
That you can open the dev card viewer and see that you have a monument card even if you have no others.

Actual:
You can only see that you have a monument card if you have some other playable dev card.

The problem with this is if you buy a monument card and could use it to win the game, you wouldn't be able to until you buy another dev card.

**Comment by enexia79** [comment]
already fixed with another issue.  Now always showing dev cards playable or not.
