### ISSUE TITLE
Implement ICatanModel

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#155]

**Comment by enexia79** [comment]
I set Client model to Implement ICatanModel but I didn't actually implement all the methods..  So I guess I gave you a start lol.

**Comment by enexia79** [comment]
I added to the IGame interface a method checkPlayerIndex(name, playerIndex) throws InvalidRequestException;  When implementing move commands you can use this to do a check if the player doing the move is the one that should  it will throw the exception for you so you don't have to worry about the response just let the CommandHandler catch it.
