### ISSUE TITLE
Implement Moves Commands

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#157]
- [x] Accept trade
- [x] Build settlement
- [x] Build City
- [x] Build road
- [x] Buy dev card
- [x] Discard cards
- [x] Finish Turn
- [x] Maritime Trade
- [x] Monopoly
- [x] Monument
- [x] Offer trade
- [x] Road Building
- [x] Rob player
- [x] Roll number
- [x] Send chat
- [x] Soldier
- [x] Year of plenty

**Comment by enexia79** [comment]
I added to the IGame interface a method checkPlayerIndex(name, playerIndex) throws InvalidRequestException;  When implementing move commands you can use this to do a check if the player doing the move is the one that should  it will throw the exception for you so you don't have to worry about the response just let the CommandHandler catch it.

**Comment by joshuata** [comment]
[ ] - Finish Turn
  [ ] - Maritime Trade
  [ ] - Offer trade
