### ISSUE TITLE
Player Waiting Controller

### ISSUE THREAD

**Issue by joshuata** [joshuata/settlers-340#82]
Implement `PlayerWaitingController`

**Comment by joshuata** [comment]
Relies on `createGame` in #81

**Comment by joshuata** [comment]
2 possible states:
* Join game with empty spaces
* Join game without empty spaces

**Comment by enexia79** [comment]
addAI isn't working.  it adds the ai but you are still stuck with the same message saying waiting on other players.  (display doesn't update or show any indication that an ai was added)

**Comment by enexia79** [comment]
fixed
